name: Unit tests

on: [push, pull_request]

jobs:
  
  tox:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3
    steps:
     - name: checkout
       uses: actions/checkout@v4

     - name: gentoo setup
       run: |
         pushd /var/db/repos || exit $?
         wget https://github.com/gentoo-mirror/gentoo/archive/master.tar.gz -O gentoo-master.tar.gz || exit $?
         tar -xvf gentoo-master.tar.gz || exit $?
         mv gentoo-master gentoo || exit $?
         popd || exit $?
         eselect profile set 1 || exit $? 

     - name: emerge deps
       run: |
         emerge dev-python/tox

     - name: run tox
       run: |
         tox run
         
