name: Unit tests

on: [push, pull_request]

jobs:
  
  meson-test:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3
    steps:
     - name: checkout
       uses: actions/checkout@v4

     - name: gentoo setup
       run: |
         wget https://github.com/gentoo-mirror/gentoo/archive/master.tar.gz || exit $?
         tar -xvf gentoo-master.tar.gz -C /var/db/repos || exit $?
         mv /var/db/repos/gentoo-master /var/db/repos/gentoo || exit $?
         eselect profile set 1 || exit $?

     - name: emerge deps
       run: |
         emerge meson pytest

     - name: run meson tests
       run: |
         meson setup build &&
         meson test -C build
         
