name: Unit tests

on: [push, pull_request]

jobs:
  
  tox:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3
    steps:
     - name: checkout
       uses: actions/checkout@v4

     - name: gentoo setup
       run: |
         # setup /var/db/repos/gentoo
         pushd /var/db/repos || exit $?
         wget https://github.com/gentoo-mirror/gentoo/archive/master.tar.gz -O gentoo-master.tar.gz || exit $?
         tar -xvf gentoo-master.tar.gz || exit $?
         mv gentoo-master gentoo || exit $?
         popd || exit $?
         # select profile
         eselect profile set 1 || exit $?
         # configure binhost
         rmdir -rf /etc/portage/binrepos.conf || exit $?
         echo '
         [binhost]
         sync-uri = https://distfiles.gentoo.org/releases/amd64/binpackages/17.1/x86-64
         ' >/etc/portage/binrepos.conf

     - name: emerge deps
       run: |
         emerge --getbinpkg dev-python/tox \
                            dev-lang/python:3.9 \
                            dev-lang/python:3.10 \
                            dev-lang/python:3.11 \
                            dev-lang/python:3.12

     - name: run tox
       run: |
         tox run
         
