name: Unit tests

on: [push, pull_request]

jobs:
  
  pytest:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3
    steps:
     - name: checkout
       uses: actions/checkout@v4

     - name: gentoo setup
       run: |
         emerge-webrsync && \
         eselect profile set 1

     - name: emerge deps
       run: |
         emerge dev-python/pytest

     - name: pytest
       run: |
         pytest -vv
         
  black:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3
    steps:
     - name: checkout
       uses: actions/checkout@v4

     - name: gentoo setup
       run: |
         emerge-webrsync && \
         eselect profile set 1

     - name: emerge deps
       run: |
         emerge dev-python/black

     - name: black
       run: |
         black --check pym/gentoolkit

  mypy:
    runs-on: ubuntu-latest
    container:
      image: gentoo/stage3
    steps:
     - name: checkout
       uses: actions/checkout@v4

     - name: gentoo setup
       run: |
         emerge-webrsync && \
         eselect profile set 1

     - name: emerge deps
       run: |
         emerge dev-python/mypy

     - name: mypy
       run: |
         mypy pym/gentoolkit
